#!/bin/bash
# wraith daemon
# chkconfig: 345 20 80
# description: wraith daemon
# processname: wraith

DAEMON_PATH="/opt/wraith-donk/"

DAEMON=wraithDaemon

NAME=wraith-donk
DESC="My daemon description"
PIDFILE=/opt/wraith-donk/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

export PATH="/usr/local/rvm/gems/ruby-2.1.0/bin:/usr/local/rvm/gems/ruby-2.1.0@global/bin:/usr/local/rvm/rubies/ruby-2.1.0/bin:$PATH"
export GEM_HOME='/usr/local/rvm/gems/ruby-2.1.0'
export GEM_PATH='/usr/local/rvm/gems/ruby-2.1.0:/usr/local/rvm/gems/ruby-2.1.0@global'
export MY_RUBY_HOME='/usr/local/rvm/rubies/ruby-2.1.0'
export IRBRC='/usr/local/rvm/rubies/ruby-2.1.0/.irbrc'
unset MAGLEV_HOME
unset RBXOPT
export RUBY_VERSION='ruby-2.1.0'

case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
        
	PID=`bundle exec ruby wraithDaemon.rb > /opt/wraith-donk/logs/wraith.log 2>&1 & echo $!`
	#echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
